// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsqedtldeuuzyqpxcdup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzcWVkdGxkZXV1enlxcHhjZHVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MTEzODAsImV4cCI6MjA2Mzk4NzM4MH0.VN_4WU2bb0pR5Bopgl_enxQK8ZNZ5nACxMBw6kYmDF0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);